firstapp/firstapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myfirstapp.urls')),
    ]

firstapp/myfirstapp/urls.py
from django.urls import path
from myfirstapp import views
from myfirstapp import views_api

app_name = 'myfirstapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('read/', views.readStudent, name='read-data-student'),
    path('create/', views.createStudent, name='create-data-student'),
    path('update/<str:id>', views.updateStudent, name='update-data-student'),
    path('delete/<str:id>', views.deleteStudent, name='delete-data-student'),

    # URLs untuk Course
    path('read/course', views.readCourse, name='read-data-course'),
    path('create/course', views.createCourse, name='create-data-course'),
    path('update/course/<str:id>', views.updateCourse, name='update-data-course'),
    path('delete/course/<str:id>', views.deleteCourse, name='delete-data-course'),

    # URLs untuk API Course
    #path('api/course', views_api.apiCourse, name='api-view-data-course'),

    # URLs untuk Consume API
    path('api/consume/course', views_api.consume_api_get, name='api-consume-get-data'),
]

firstapp/myfirstapp/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.functions import RandomUUID
from django.utils import timezone
from django.utils.html import escape, mark_safe


# Create your models here.
class AccountUser(models.Model):
    account_user_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    account_user_related_user = models.CharField(max_length=255, null=False, editable=False)
    account_user_fullname = models.CharField(max_length=255, null=False, editable=False)
    account_user_student_number = models.CharField(max_length=20, null=False)
    account_user_email = models.CharField(max_length=255,null=False, default='default@example.com')
    account_user_created_by = models.CharField(max_length=255, null=False)
    account_user_created_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)
    account_user_updated_by = models.CharField(max_length=255, null=True)
    account_user_updated_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)

    def __str__(self):
        return self.account_user_related_user

    def __unicode__(self):
        return '%s' % self.account_user_related_user

    @property    
    def friendly_profile(self):
        return mark_safe(u"%s <%s>") % (
            escape(self.account_user_id), escape(self.account_user_related_user),            
            escape(self.account_user_fullname), escape(self.account_user_student_number),            
            escape(self.account_user_created_by), escape(self.account_user_created_date),            
            escape(self.account_user_updated_by), escape(self.account_user_updated_date),
        )

    class Meta:
        ordering = ('account_user_related_user',)
        indexes = [models.Index(
            fields=[
                'account_user_id',
                'account_user_related_user']), ]
        
class Course(models.Model):
    course_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    course_name = models.CharField(max_length=255, null=False, editable=False)
    course_created_by = models.CharField(max_length=255, null=False)
    course_created_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)
    course_updated_by = models.CharField(max_length=255, null=True)
    course_updated_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)

    def __str__(self):
        return self.course_related_user

    def __unicode__(self):
        return '%s' % self.course_related_user

    @property    
    def friendly_profile(self):
        return mark_safe(u"%s <%s>") % (
            escape(self.course_id), 
            escape(self.course_student_number),            
            escape(self.course_created_by), 
            escape(self.course_created_date),           
            escape(self.course_updated_by),
            escape(self.course_updated_date),
        )

    class Meta:
        ordering = ('course_id',)
        indexes = [models.Index(
            fields=[
                'course_id']), ]


class AttendingCourse(models.Model):
    attending_course_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    attending_courseid = models.ForeignKey("Course", on_delete=models.CASCADE)
    attending_account_profile_id = models.CharField(max_length=255, null=False, editable=False)
    attending_course_created_by = models.CharField(max_length=255, null=False)
    attending_course_created_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)
    attending_course_updated_by = models.CharField(max_length=255, null=True)
    attending_course_updated_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)

    def __str__(self):
        return self.attending_account_profile_id

    def __unicode__(self):
        return '%s' % self.attending_account_profile_id

    @property    
    def friendly_profile(self):
        return mark_safe(u"%s <%s>") % (
            escape(self.attending_course_id), 
            escape(self.attending_courseid),            
            escape(self.attending_account_profile_id),            
            escape(self.attending_course_created_by), 
            escape(self.attending_course_created_date),            
            escape(self.attending_course_updated_by), 
            escape(self.attending_course_updated_date)
        )

    class Meta:
        ordering = ('attending_course_id',)
        indexes = [models.Index(
            fields=[
                'attending_course_id', 'attending_courseid']), ]


firstapp/myfirstapp/forms.py
from django import forms
from myfirstapp.models import AccountUser


class StudentRegisterForm(forms.Form):
    fullname = forms.CharField(
        label='Nama Lengkap',
        label_suffix=" : ",
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'John Smith'}
        ),
        help_text="Nama lengkap mahasiswa",
        error_messages={'required': "Harus Diisi"}
    )
    nim = forms.CharField(
        label='Nim',
        label_suffix=" : ",
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '102988444'}
        ),
        help_text="Nomor induk mahasiswa",
        error_messages={'required': "Harus Diisi"}
    )
    email = forms.CharField(
        label='Email',
        label_suffix=" : ",
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'john@smith.co'}
        ),
        help_text="Email aktif",
        error_messages={'required': "Harus Diisi"}
    )

    class Meta:
        model = AccountUser
        fields = ('account_user_fullname', 'account_user_student_number')

    def clean(self):
        super(StudentRegisterForm, self).clean()

        fullname = self.cleaned_data.get("fullname")
        if not fullname:
            self._errors['fullname'] = self.error_class(['Harus di isi!'])

        nim = self.cleaned_data.get("nim")
        if not nim:
            self._errors['nim'] = self.error_class(['Harus di isi!'])

        email = self.cleaned_data.get("email")
        if not email:
            self._errors['email'] = self.error_class(['Harus di isi!'])

firstapp/myfirstapp/views.py
import sys
from django.contrib import messages
from django.db.models.signals import post_save
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.db.models import Q
from django.contrib.auth.models import User
from myfirstapp.models import AccountUser
from myfirstapp.signals import check_nim
from myfirstapp.forms import StudentRegisterForm


def home(request):
    return render(request,'home.html')

def readCourse(request):
    #mengambil data dari models.py yang Course
    data = Course.objects.filter()[:1]

    konteks = {'data list' : data}

    return render(request,'course.html', konteks)

def createCourse(request):
    return render(request,'home.html')


def updateCourse(request):
    return render(request,'home.html')

@csrf_protect
def deleteCourse(request):
    data = Course.objects.get(course_id=id)
    if User:
        data.delete()
        messages.success(request,'data berhasil di hapus')
        return redirect('myfirstapp:read-data-course')
    else:
         messages.success(request, 'Data Tidak ada')
         return redirect('myfirstapp:read-data-course')

def readStudent(request):
    data = AccountUser.objects.all()
    context = {'data_list': data}
    return render(request, 'index.html', context)


@csrf_protect
def createStudent(request):
    if request.method == 'POST':
        form = StudentRegisterForm(request.POST)
        if form.is_valid():
            post_save.disconnect(check_nim)
            form.fullname = form.cleaned_data.get("fullname")
            form.nim = form.cleaned_data.get("nim")
            form.email = form.cleaned_data.get("email")
            post_save.send(
                sender=AccountUser,
                created=None,
                instance=form,
                dispatch_uid="check_nim"
            )
            messages.success(request, 'Data Berhasil disimpan')
            return redirect('myfirstapp:read-data-student')
    else:
        form = StudentRegisterForm()

    return render(request, 'form.html', {'form': form})


@csrf_protect
def updateStudent(request, id):
    # Create Your Task Here...
    messages.success(request, 'Data Berhasil disimpan')
    return redirect('myfirstapp:read-data-student')


@csrf_protect
def deleteStudent(request, id):
    member = AccountUser.objects.get(account_user_related_user=id)
    user = User.objects.get(username=id)
    member.delete()
    user.delete()
    messages.success(request, 'Data Berhasil dihapus')
    return redirect('myfirstapp:read-data-student')

firstapp/myfirstapp/templates/Api-get.html
{% load static %}
{% block content %}
{% if messages %}
    <div>
        {% for message in messages %}
            <strong>{{ message }}</strong>
        {% endfor %}
    </div> 
    {% endif %}

<style>
    thead{
        background-color: rgb(36, 28, 184);
        color: red;
    }
</style>

<table border="10">
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>username</th>
            <th>email</th>
            <th>phone</th>
            <th>address</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for obj in data %}
            <td>{{ obj.id }}</td>
            <td>{{ obj.name }}</td>
            <td>{{ obj.username }}</td>
            <td>{{ obj.email }}</td>
            <td>{{ obj.phone }}</td>
            <td>{{ obj.address }}</td>
        </tr>
        {% empty %}
            <h1>Data Masih Kosong</h1>
            {% endfor %} 
    </tbody>
</table>
{% endblock %} 

firstapp/myfirstapp/templates/form.html
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="main_business">
                <div class="col-md-12">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ form.errors }}</strong>
                        </div>
                        <br>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <form method="post" id="create-form" name="create-form">
        {% csrf_token %}
        <div>
            <label>Input Nama Lengkap</label>
            <input type="text" name="fullname" id="fullname">
        </div>
        <div>
            <label>Input NIM Lengkap</label>
            <input type="text" name="nim" id="nim">
        </div>
        <div>
            <label>Input Email Lengkap</label>
            <input type="email" name="email" id="email">
        </div>
        <div class="panel-footer text-center">
            <button class="btn btn-primary m-top-20">
                Simpan
            </button>
        </div>
    </form>
{% endblock %}

firstapp/myfirstapp/templates/index.html
{% load static %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                <strong>{{ message }}</strong>
            {% endfor %}
        </div>
    {% endif %}
    
    <a href="{% url 'myfirstapp:create-data-student' %}">Create</a>
    <table border="1">
        <thead>
            <tr>
                <td>NIM</td>
                <td>Nama</td>
                <td>e-mail</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            {% for obj in data_list %}
                <tr>
                    <td>{{ obj.account_user_student_number }}</td>
                    <td>{{ obj.account_user_fullname }}</td>
                    <td>{{ obj.account_user_related_user }}</td>
                    <td>
                        <a href="{% url 'myfirstapp:update-data-student' obj.account_user_related_user %}">Update</a>
                        <br>
                        <a href="{% url 'myfirstapp:delete-data-student' obj.account_user_related_user %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">
                        <h1>Data masih kosong</h1>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

firstapp/myfirstapp/templates/update.html
<!-- update.html -->
{% extends 'update-data-student.html' %}

{% block content %}
<div class="container">
  <h2>Update Student Data</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
</div>
{% endblock %}